services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    # IMPORTANT:
    # - Provide cloud endpoints via environment variables in backend/.env
    #   - REDIS_URL=rediss://:PASSWORD@HOST:6380/0
    #   - NEO4J_URI=neo4j+s://YOUR_INSTANCE.databases.neo4j.io
    #   - MONGO_URI=mongodb+srv://USER:PASS@CLUSTER.mongodb.net/DB
    #   - PINECONE_API_KEY=... and index configured
    restart: unless-stopped
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

  celery-worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["celery", "-A", "app.celery_worker.celery_app", "worker", "--loglevel=info", "-P", "solo"]
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    restart: unless-stopped

  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A app.celery_worker.celery_app beat --loglevel=info
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
    restart: unless-stopped
