name: Project Audit

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install minimal deps
        run: |
          python -m pip install --upgrade pip
          # Only stdlib used by the tool; install extras if needed

      - name: Run audit (dry-run)
        run: |
          python tools/clean_and_audit.py --root . --report reports --backup --delete-caches no --strip-comments no

      - name: Upload audit artifacts
        uses: actions/upload-artifact@v4
        with:
          name: audit-reports
          path: reports/
          if-no-files-found: warn
